In [1]:
# from __future__ import print_function
import torch

<h2> Getting Started </h2>

<h3>Tensors</h3>

In [2]:
# creates empty tensors

In [3]:
# 1d array
x = torch.empty(3)
print(x)
print(x.size())

tensor([3.7938e+31, 4.5691e-41, 2.5530e-36])
torch.Size([3])


In [4]:
# 2d array
x = torch.empty(5, 3)
print(x)
print(x.size())

tensor([[ 3.7938e+31,  4.5691e-41,  3.7938e+31],
        [ 4.5691e-41,  1.7228e-34, -4.6046e-26],
        [-1.8419e-25,  9.2737e-41,  2.1163e-37],
        [ 2.1246e-37,  1.9336e-37,  1.7228e-34],
        [-1.1788e-23, -4.7151e-23,  9.2737e-41]])
torch.Size([5, 3])


In [5]:
# 3d array
x = torch.empty(2, 3, 4)  # depth, height, width
print(x)
print(x.size())

tensor([[[ 2.5291e-36,  0.0000e+00,  2.5530e-36,  0.0000e+00],
         [ 1.7228e-34,  4.6046e-26,  1.8419e-25,  9.2737e-41],
         [ 2.1163e-37,  2.1246e-37,  1.9336e-37,  1.7228e-34]],

        [[ 1.1788e-23,  4.7151e-23,  1.1351e-43,  0.0000e+00],
         [ 2.5368e-36,  0.0000e+00,  3.7938e+31,  4.5691e-41],
         [ 0.0000e+00,  0.0000e+00, -5.4746e-26, -3.3905e-06]]])
torch.Size([2, 3, 4])


In [6]:
# creates random tensors

In [7]:
# Returns a tensor filled with random numbers from a uniform 
# distribution on the interval [0, 1)
x = torch.rand(5, 3)
print(x)

tensor([[0.4496, 0.0596, 0.0079],
        [0.0906, 0.8627, 0.5872],
        [0.4498, 0.4027, 0.7411],
        [0.1303, 0.3239, 0.0855],
        [0.6922, 0.0975, 0.0152]])


In [8]:
# Returns a tensor filled with random numbers from a normal 
# distribution with mean 0 and variance 1 (also called the standard 
# normal distribution).
x = torch.randn(5, 3)
print(x)

tensor([[ 0.2669, -1.3879, -0.6508],
        [-1.3244, -0.1889,  1.5667],
        [-0.6063,  2.0061,  1.3906],
        [-1.2492, -0.4198, -2.5594],
        [ 0.1090,  0.3230,  1.9377]])


In [9]:
# zeros and ones

In [10]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
# creates tensors from data

In [13]:
# from arrays
x = torch.tensor([5.5, 3])
print(x)
print(x.size())

print()

x = torch.tensor([[5.5, 3]])
print(x)
print(x.size())

print()

x = torch.tensor([[[5.5, 3]]])
print(x)
print(x.size())

tensor([5.5000, 3.0000])
torch.Size([2])

tensor([[5.5000, 3.0000]])
torch.Size([1, 2])

tensor([[[5.5000, 3.0000]]])
torch.Size([1, 1, 2])


In [14]:
# creates a tensor based on an existing tensor. 
# These methods will reuse properties of the input tensor, 
# e.g. dtype, device, layout unless new values are provided by user

In [45]:
# Returns a Tensor of size size filled with 1. By default, the 
# returned Tensor has the same torch.dtype and torch.device as this 
# tensor.
print(x)
print(x.dtype, x.device, x.layout)

print()

x = x.new_ones(5, 3)

print(x)
print(x.dtype, x.device, x.layout)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32 cpu torch.strided

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32 cpu torch.strided


In [46]:
# Returns a tensor filled with the scalar value 1, with the same size 
# as input. torch.ones_like(input) is equivalent to 
# torch.ones(input.size(), dtype=input.dtype, layout=input.layout, 
# device=input.device).
print(x)
print(x.size())
print(x.dtype, x.device, x.layout)

print()

x = torch.rand_like(x)

print(x)
print(x.size())
print(x.dtype, x.device, x.layout)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([5, 3])
torch.float32 cpu torch.strided

tensor([[0.5747, 0.3078, 0.9780],
        [0.6040, 0.3704, 0.7363],
        [0.3471, 0.4078, 0.3106],
        [0.3244, 0.9992, 0.3698],
        [0.4557, 0.6353, 0.5955]])
torch.Size([5, 3])
torch.float32 cpu torch.strided


In [54]:
# from numpy
import numpy as np

x = np.array([[2, 3, 3]], dtype=np.double)
print(x)
print(x.dtype)

print()

x = torch.tensor(x)

print(x)
print(x.dtype)

[[2. 3. 3.]]
float64

tensor([[2., 3., 3.]], dtype=torch.float64)
torch.float64


In [55]:
# specifies data type

In [56]:
x = torch.empty(2, 3, dtype=torch.long)
print(x)

tensor([[                  0,          1231241120, 4613937818241073152],
        [4575657222473777152, 4575657222473777152, 4575657222473777152]])


In [57]:
# gets size
# torch.Size is in fact a tuple, so it supports all tuple operations.

In [58]:
print(x.size())
print(x.size()[0])

torch.Size([2, 3])
2


<h3>Operations</h3>

In [59]:
# addition

In [60]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [61]:
# uses operators
print(x + y)

tensor([[1.7294, 0.4665, 1.8198],
        [0.6796, 0.3177, 0.6097],
        [0.8051, 0.7553, 0.3181],
        [0.8829, 0.8260, 0.0563],
        [1.2183, 0.7368, 1.0095]])


In [62]:
# uses functions
print(torch.add(x, y))

tensor([[1.7294, 0.4665, 1.8198],
        [0.6796, 0.3177, 0.6097],
        [0.8051, 0.7553, 0.3181],
        [0.8829, 0.8260, 0.0563],
        [1.2183, 0.7368, 1.0095]])


In [63]:
# provides an output tensor as argument
result = torch.empty(x.size())

torch.add(x, y, out=result)
print(result)

tensor([[1.7294, 0.4665, 1.8198],
        [0.6796, 0.3177, 0.6097],
        [0.8051, 0.7553, 0.3181],
        [0.8829, 0.8260, 0.0563],
        [1.2183, 0.7368, 1.0095]])


In [64]:
# in place
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.
print(y.add_(x))

tensor([[1.7294, 0.4665, 1.8198],
        [0.6796, 0.3177, 0.6097],
        [0.8051, 0.7553, 0.3181],
        [0.8829, 0.8260, 0.0563],
        [1.2183, 0.7368, 1.0095]])


In [65]:
# indexing

In [66]:
x = torch.tensor([1, 2, 3])
print(x)
print(x[0])

print()

x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]])
print(x)
print(x[0])
print(x[:, 0])

print()

x = torch.tensor([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]]])
print(x)
print(x[0])
print(x[:, 0])
print(x[:, :, 0])

tensor([1, 2, 3])
tensor(1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor([1, 4])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([[ 1,  4],
        [ 7, 10]])


In [30]:
# resizing

In [67]:
x = torch.randn(2, 3)
print(x)
print(x.size())

print()

x = x.view(6)
print(x)
print(x.size())

print()

x = x.view(-1, 6)
print(x)
print(x.size())

tensor([[-0.3961,  0.2042, -0.9014],
        [ 1.0597,  0.2303,  1.0633]])
torch.Size([2, 3])

tensor([-0.3961,  0.2042, -0.9014,  1.0597,  0.2303,  1.0633])
torch.Size([6])

tensor([[-0.3961,  0.2042, -0.9014,  1.0597,  0.2303,  1.0633]])
torch.Size([1, 6])


In [68]:
# If you have a one element tensor, use .item() to get the value as a 
# Python number

In [69]:
x = torch.tensor(2)
print(x)
print(x.item())

print()

x = torch.tensor([3])
print(x)
print(x.item())
print(x[0])
print(x[0].item())

print()

x = torch.tensor([[2]])
print(x)
print(x.item())
print(x[0])
print(x[0].item())
print(x[0][0])
print(x[0][0].item())

tensor(2)
2

tensor([3])
3
tensor(3)
3

tensor([[2]])
2
tensor([2])
2
tensor(2)
2


<h2>Numpy Bridge</h2>

In [70]:
# The Torch Tensor and NumPy array will share their underlying memory 
# locations (if the Torch Tensor is on CPU), and changing one will
# change the other.

<h3>Converting a Torch Tensor to a NumPy Array</h3>

In [35]:
a_torch = torch.ones(5)
print(a_torch)

a_numpy = a_torch.numpy()
print(a_numpy)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [36]:
print(a_numpy)
print(a_torch)

print()

a_torch.add_(1)

print(a_numpy)  # a_numpy also changed!
print(a_torch)  

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])


<h3>Converting NumPy Array to Torch Tensor</h3>

In [37]:
a_numpy = np.ones(5)
print(a_numpy)

a_torch = torch.from_numpy(a_numpy)
print(a_torch)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [38]:
print(a_torch)
print(a_numpy)

print()

np.add(a_numpy, 1, out=a_numpy)

print(a_torch)
print(a_numpy)  # a_torch also changed!

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


In [39]:
# torch.from_numpy(numpy_array) is different from 
# torch.tensor(numpy_array). the latter won't share memory with the 
# original numpy array
a_numpy = np.ones(5)
print(a_numpy)

a_torch = torch.tensor(a_numpy)
print(a_torch)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
print(a_torch)
print(a_numpy)

print()

np.add(a_numpy, 1, out=a_numpy)

print(a_torch)
print(a_numpy)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


<h2>CUDA Tensors</h2>

In [41]:
# Tensors can be moved onto any device using the .to method.

In [42]:
device = None
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
    
print(device)

cuda


In [43]:
print(x, x.dtype, x.device)

print()

x = torch.ones_like(x, dtype=torch.double, device=device)
print(x, x.dtype, x.device)

print()

x = x.to(dtype=torch.float, device="cpu")
print(x, x.dtype, x.device)

tensor([[2]]) torch.int64 cpu

tensor([[1.]], device='cuda:0', dtype=torch.float64) torch.float64 cuda:0

tensor([[1.]]) torch.float32 cpu
